format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.git-wip}\
$python\
$cmd_duration\
$status\
$line_break\
$character"""

# insert a blank line between prompts
add_newline = true

[character]
success_symbol = "[➜](#98c379)"
error_symbol = "[➜](#e06c75)"

[directory]
style = ""
read_only = "  "
read_only_style = "bg:#61afef fg:white bold"
truncate_to_repo = true
format = """
[](bg:none fg:#e5c07b)\
[ ](bg:#e5c07b fg:black)\
[$read_only]($read_only_style)\
[ $path ](bg:#333333 fg:#a8b1bf)\
[](bg:none fg:#333333) \
"""

[git_branch]
symbol = " "
style = "#56b6c2"
format = "[$symbol$branch]($style) "

[git_commit]
style = "bold #61afef"

[git_state]
style = "bold #e5c07b"
format = "[$state($progress_current/$progress_total)]($style) "

[git_status]
style = "#868c96"
format = "[$all_status$ahead_behind]($style) "
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
stashed = " "
conflicted = "✗"
untracked = " "
modified = " "
renamed = " "
deleted = " "
staged = " "

[status]
style = "#e06c75"
format = "[$symbol$status]($style) "
symbol = " "
map_symbol = false
pipestatus = false
disabled = false

[cmd_duration]
format = "[took](#868c96) [$duration]($style) "
style = "#7c7cff"

[custom.git-wip]
description = "Display a warning if the latest commit in the current git repo is WIP."
when = "git log -n 1 2>/dev/null | grep -q -c '\\-\\-wip\\-\\-'"
command = "echo wip"
style = "bold #e5c07b"
symbol = " "
